In [ ]:
import csv
with open("movies.csv") as f:
    data = list(csv.reader(f))
    print(data)

[['title', 'industry', 'release_year', 'imdb_rating', 'studio', 'budget', 'revenue', 'unit', 'currency', 'language'], ['Pather Panchali', 'Bollywood', '1955', '8.3', 'Government of West Bengal', '70000', '100000', 'Thousands', 'INR', 'Bengali'], ['Doctor Strange in the Multiverse of Madness', 'Hollywood', '2022', '7', 'Marvel Studios', '200', '954.8', 'Millions', 'USD', 'English'], ['Thor: The Dark World ', 'Hollywood', '2013', '6.8', 'Marvel Studios', '165', '644.8', 'Millions', 'USD', 'English'], ['Thor: Ragnarok ', 'Hollywood', '2017', '7.9', 'Marvel Studios', '180', '854', 'Millions', 'USD', 'English'], ['Thor: Love and Thunder ', 'Hollywood', '2022', '6.8', 'Marvel Studios', '250', '670', 'Millions', 'USD', 'English'], ['The Shawshank Redemption', 'Hollywood', '1994', '9.3', 'Castle Rock Entertainment', '25', '73.3', 'Millions', 'USD', 'English'], ['Interstellar', 'Hollywood', '2014', '8.6', 'Warner Bros. Pictures', '165', '701.8', 'Millions', 'USD', 'English'], ['The Pursuit of Happyness', 'Hollywood', '2006', '8', 'Columbia Pictures', '55', '307.1', 'Millions', 'USD', 'English'], ['Gladiator', 'Hollywood', '2000', '8.5', 'Universal Pictures  ', '103', '460.5', 'Millions', 'USD', 'English'], ['Titanic', 'Hollywood', '1997', '7.9', 'Paramount Pictures', '200', '2202', 'Millions', 'USD', 'English'], ["It's a Wonderful Life", 'Hollywood', '1946', '8.6', 'Liberty Films', '3.18', '3.3', 'Millions', 'USD', 'English'], ['Avatar', 'Hollywood', '2009', '7.8', '20th Century Fox', '237', '2847', 'Millions', 'USD', 'English'], ['The Godfather', 'Hollywood', '1972', '9.2', 'Paramount Pictures', '7.2', '291', 'Millions', 'USD', 'English'], ['The Dark Knight', 'Hollywood', '2008', '9', 'Syncopy', '185', '1006', 'Millions', 'USD', 'English'], ["Schindler's List", 'Hollywood', '1993', '9', 'Universal Pictures', '22', '322.2', 'Millions', 'USD', 'English'], ['Jurassic Park', 'Hollywood', '1993', '8.2', 'Universal Pictures', '63', '1046', 'Millions', 'USD', 'English'], ['Parasite', 'Hollywood', '2019', '8.5', '', '15.5', '263.1', 'Millions', 'USD', 'English'], ['Avengers: Endgame', 'Hollywood', '2019', '8.4', 'Marvel Studios', '400', '2798', 'Millions', 'USD', 'English'], ['Avengers: Infinity War', 'Hollywood', '2018', '8.4', 'Marvel Studios', '400', '2048', 'Millions', 'USD', 'English'], ['Captain America: The First Avenger', 'Hollywood', '2011', '6.9', 'Marvel Studios', '216.7', '370.6', 'Millions', 'USD', 'English'], ['Captain America: The Winter Soldier', 'Hollywood', '2014', '7.8', 'Marvel Studios', '177', '714.4', 'Millions', 'USD', 'English'], ['Dilwale Dulhania Le Jayenge', 'Bollywood', '1995', '8', 'Yash Raj Films', '400', '2000', 'Millions', 'INR', 'Hindi'], ['3 Idiots', 'Bollywood', '2009', '8.4', 'Vinod Chopra Films', '550', '4000', 'Millions', 'INR', 'Hindi'], ['Kabhi Khushi Kabhie Gham', 'Bollywood', '2001', '7.4', 'Dharma Productions', '390', '1360', 'Millions', 'INR', 'Hindi'], ['Bajirao Mastani ', 'Bollywood', '2015', '7.2', '', '1.4', '3.5', 'Billions', 'INR', 'Hindi'], ['Taare Zameen Par', 'Bollywood', '2007', '8.3', '', '120', '1350', 'Millions', 'INR', 'Hindi'], ['Munna Bhai M.B.B.S.', 'Bollywood', '2003', '8.1', 'Vinod Chopra Productions', '100', '410', 'Millions', 'INR', 'Hindi'], ['PK', 'Bollywood', '2014', '8.1', 'Vinod Chopra Films', '850', '8540', 'Millions', 'INR', 'Hindi'], ['Sanju', 'Bollywood', '2018', 'NULL', 'Vinod Chopra Films', '1', '5.9', 'Billions', 'INR', 'Hindi'], ['The Kashmir Files', 'Bollywood', '2022', '8.3', 'Zee Studios', '250', '3409', 'Millions', 'INR', 'Hindi'], ['Bajrangi Bhaijaan', 'Bollywood', '2015', '8.1', 'Salman Khan Films', '900', '11690', 'Millions', 'INR', 'Hindi'], ['Race 3', 'Bollywood', '2018', '1.9', 'Salman Khan Films', '1.8', '3.1', 'Billions', 'INR', 'Hindi'], ['Shershaah', 'Bollywood', '2021', '8.4', 'Dharma Productions', '500', '950', 'Millions', 'INR', 'Hindi'], ['K.G.F: Chapter 2', 'Bollywood', '2022', '8.4', 'Hombale Films', '1', '12.5', 'Billions', 'INR', 'Kannada'], ['Pushpa: The Rise - Part 1', 'Bollywood', '2021', '7.6', 'Mythri Movie Makers', '2', '3.6', 'Billions', 'INR', 'Telugu'], ['RRR', 'Bollywood', '2022', '8', 'DVV Entertainment', '5.5', '12', 'Billions', 'INR', 'Telugu'], ['Baahubali: The Beginning', 'Bollywood', '2015', '8', 'Arka Media Works', '1.8', '6.5', 'Billions', 'INR', 'Telugu']]

In [4]:
header =  data[0]
data = data[1:]

In [7]:
import csv

def calculate_rating_stats(data, industry=None):
    rating = []
    for row in data:
        if row[3]!='NULL' and ( not industry or row[1]== industry):
            rating.append(float(row[3]))

    max_rating=max(rating)
    min_rating=min(rating)
    avg_rating=sum(rating)/len(rating)
    return max_rating, min_rating,avg_rating

max_rating, min_rating, avg_rating=calculate_rating_stats(data)
print(f"for all movies the minmum rating is {min_rating}, maximum rating is {max_rating}, average rating is {avg_rating}")

max_rating, min_rating, avg_rating=calculate_rating_stats(data,industry="Bollywood")
print(f"for bollywood movies the minmum rating is {min_rating}, maximum rating is {max_rating}, average rating is {avg_rating}")

max_rating, min_rating, avg_rating=calculate_rating_stats(data,industry="Hollywood")
print(f"for hollywood movies the minmum rating is {min_rating}, maximum rating is {max_rating}, average rating is {avg_rating}")

for all movies the minmum rating is 1.9, maximum rating is 9.3, average rating is 7.919444444444445
for bollywood movies the minmum rating is 1.9, maximum rating is 8.4, average rating is 7.65625
for hollywood movies the minmum rating is 6.8, maximum rating is 9.3, average rating is 8.129999999999999

In [11]:
import pandas as pd
df = pd.read_csv("movies.csv")
df.head()

,title,industry,release_year,imdb_rating,studio,budget,revenue,unit,currency,language
0,Pather Panchali,Bollywood,1955,8.3,Government of West Bengal,70000.0,100000.0,Thousands,INR,Bengali
1,Doctor Strange in the Multiverse of Madness,Hollywood,2022,7.0,Marvel Studios,200.0,954.8,Millions,USD,English
2,Thor: The Dark World,Hollywood,2013,6.8,Marvel Studios,165.0,644.8,Millions,USD,English
3,Thor: Ragnarok,Hollywood,2017,7.9,Marvel Studios,180.0,854.0,Millions,USD,English
4,Thor: Love and Thunder,Hollywood,2022,6.8,Marvel Studios,250.0,670.0,Millions,USD,English

In [13]:
df[2:6]

,title,industry,release_year,imdb_rating,studio,budget,revenue,unit,currency,language
2,Thor: The Dark World,Hollywood,2013,6.8,Marvel Studios,165.0,644.8,Millions,USD,English
3,Thor: Ragnarok,Hollywood,2017,7.9,Marvel Studios,180.0,854.0,Millions,USD,English
4,Thor: Love and Thunder,Hollywood,2022,6.8,Marvel Studios,250.0,670.0,Millions,USD,English
5,The Shawshank Redemption,Hollywood,1994,9.3,Castle Rock Entertainment,25.0,73.3,Millions,USD,English

In [15]:
df.shape

(37, 10)

In [17]:
df.imdb_rating.head(5)

0    8.3
1    7.0
2    6.8
3    7.9
4    6.8
Name: imdb_rating, dtype: float64

In [18]:
df["imdb_rating"].head(5)

0    8.3
1    7.0
2    6.8
3    7.9
4    6.8
Name: imdb_rating, dtype: float64

In [19]:
type(df.imdb_rating)

pandas.Series

In [20]:
type(df)

pandas.DataFrame

In [21]:
df.imdb_rating.min(),df.imdb_rating.max(),df.imdb_rating.mean()

(np.float64(1.9), np.float64(9.3), np.float64(7.919444444444445))

In [22]:
df[df.industry=="Bollywood"].head()

,title,industry,release_year,imdb_rating,studio,budget,revenue,unit,currency,language
0,Pather Panchali,Bollywood,1955,8.3,Government of West Bengal,70000.0,100000.0,Thousands,INR,Bengali
21,Dilwale Dulhania Le Jayenge,Bollywood,1995,8.0,Yash Raj Films,400.0,2000.0,Millions,INR,Hindi
22,3 Idiots,Bollywood,2009,8.4,Vinod Chopra Films,550.0,4000.0,Millions,INR,Hindi
23,Kabhi Khushi Kabhie Gham,Bollywood,2001,7.4,Dharma Productions,390.0,1360.0,Millions,INR,Hindi
24,Bajirao Mastani,Bollywood,2015,7.2,NaN,1.4,3.5,Billions,INR,Hindi

In [23]:
df[df["industry"]=="Hollywood"].head()

,title,industry,release_year,imdb_rating,studio,budget,revenue,unit,currency,language
1,Doctor Strange in the Multiverse of Madness,Hollywood,2022,7.0,Marvel Studios,200.0,954.8,Millions,USD,English
2,Thor: The Dark World,Hollywood,2013,6.8,Marvel Studios,165.0,644.8,Millions,USD,English
3,Thor: Ragnarok,Hollywood,2017,7.9,Marvel Studios,180.0,854.0,Millions,USD,English
4,Thor: Love and Thunder,Hollywood,2022,6.8,Marvel Studios,250.0,670.0,Millions,USD,English
5,The Shawshank Redemption,Hollywood,1994,9.3,Castle Rock Entertainment,25.0,73.3,Millions,USD,English

In [25]:
df_b=df[df.industry=="Bollywood"]
df_h=df[df["industry"]=="Hollywood"]
print(df_b.imdb_rating.min(),df_b.imdb_rating.max(),df_b.imdb_rating.mean())
print(df_h.imdb_rating.min(),df_h.imdb_rating.max(),df_h.imdb_rating.mean())

1.9 8.4 7.656250000000001
6.8 9.3 8.130000000000003

In [26]:
df.columns

Index(['title', 'industry', 'release_year', 'imdb_rating', 'studio', 'budget',
       'revenue', 'unit', 'currency', 'language'],
      dtype='str')

In [27]:
df.industry.unique()

<StringArray>
['Bollywood', 'Hollywood']
Length: 2, dtype: str

In [28]:
df["language"].unique()

<StringArray>
['Bengali', 'English', 'Hindi', 'Kannada', 'Telugu']
Length: 5, dtype: str

In [29]:
df.industry.value_counts()

industry
Hollywood    20
Bollywood    17
Name: count, dtype: int64

In [30]:
df["language"].value_counts()

language
English    20
Hindi      12
Telugu      3
Bengali     1
Kannada     1
Name: count, dtype: int64

In [31]:
df.language.value_counts()

language
English    20
Hindi      12
Telugu      3
Bengali     1
Kannada     1
Name: count, dtype: int64

In [32]:
df[["title","imdb_rating","industry"]]

                                          title  imdb_rating   industry
0                               Pather Panchali          8.3  Bollywood
1   Doctor Strange in the Multiverse of Madness          7.0  Hollywood
2                         Thor: The Dark World           6.8  Hollywood
3                               Thor: Ragnarok           7.9  Hollywood
4                       Thor: Love and Thunder           6.8  Hollywood
5                      The Shawshank Redemption          9.3  Hollywood
6                                  Interstellar          8.6  Hollywood
7                      The Pursuit of Happyness          8.0  Hollywood
8                                     Gladiator          8.5  Hollywood
9                                       Titanic          7.9  Hollywood
10                        It's a Wonderful Life          8.6  Hollywood
11                                       Avatar          7.8  Hollywood
12                                The Godfather          9.2  Hollywood
13                              The Dark Knight          9.0  Hollywood
14                             Schindler's List          9.0  Hollywood
15                                Jurassic Park          8.2  Hollywood
16                                     Parasite          8.5  Hollywood
17                            Avengers: Endgame          8.4  Hollywood
18                       Avengers: Infinity War          8.4  Hollywood
19           Captain America: The First Avenger          6.9  Hollywood
20          Captain America: The Winter Soldier          7.8  Hollywood
21                  Dilwale Dulhania Le Jayenge          8.0  Bollywood
22                                     3 Idiots          8.4  Bollywood
23                     Kabhi Khushi Kabhie Gham          7.4  Bollywood
24                             Bajirao Mastani           7.2  Bollywood
25                             Taare Zameen Par          8.3  Bollywood
26                          Munna Bhai M.B.B.S.          8.1  Bollywood
27                                           PK          8.1  Bollywood
28                                        Sanju          NaN  Bollywood
29                            The Kashmir Files          8.3  Bollywood
30                            Bajrangi Bhaijaan          8.1  Bollywood
31                                       Race 3          1.9  Bollywood
32                                    Shershaah          8.4  Bollywood
33                             K.G.F: Chapter 2          8.4  Bollywood
34                    Pushpa: The Rise - Part 1          7.6  Bollywood
35                                          RRR          8.0  Bollywood
36                     Baahubali: The Beginning          8.0  Bollywood

In [35]:
df[["imdb_rating","industry"]].value_counts()

imdb_rating  industry
8.3          Bollywood    3
8.0          Bollywood    3
8.4          Bollywood    3
8.1          Bollywood    3
6.8          Hollywood    2
7.9          Hollywood    2
8.6          Hollywood    2
8.5          Hollywood    2
7.8          Hollywood    2
9.0          Hollywood    2
8.4          Hollywood    2
7.0          Hollywood    1
9.3          Hollywood    1
8.0          Hollywood    1
9.2          Hollywood    1
8.2          Hollywood    1
6.9          Hollywood    1
7.4          Bollywood    1
7.2          Bollywood    1
1.9          Bollywood    1
7.6          Bollywood    1
Name: count, dtype: int64

In [38]:
(df.release_year >=2000) & (df.release_year <= 2010)

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7      True
8      True
9     False
10    False
11     True
12    False
13     True
14    False
15    False
16    False
17    False
18    False
19    False
20    False
21    False
22     True
23     True
24    False
25     True
26     True
27    False
28    False
29    False
30    False
31    False
32    False
33    False
34    False
35    False
36    False
Name: release_year, dtype: bool

In [40]:
df[((df.release_year >=2000) & (df.release_year <= 2010))]

,title,industry,release_year,imdb_rating,studio,budget,revenue,unit,currency,language
7,The Pursuit of Happyness,Hollywood,2006,8.0,Columbia Pictures,55.0,307.1,Millions,USD,English
8,Gladiator,Hollywood,2000,8.5,Universal Pictures,103.0,460.5,Millions,USD,English
11,Avatar,Hollywood,2009,7.8,20th Century Fox,237.0,2847.0,Millions,USD,English
13,The Dark Knight,Hollywood,2008,9.0,Syncopy,185.0,1006.0,Millions,USD,English
22,3 Idiots,Bollywood,2009,8.4,Vinod Chopra Films,550.0,4000.0,Millions,INR,Hindi
23,Kabhi Khushi Kabhie Gham,Bollywood,2001,7.4,Dharma Productions,390.0,1360.0,Millions,INR,Hindi
25,Taare Zameen Par,Bollywood,2007,8.3,NaN,120.0,1350.0,Millions,INR,Hindi
26,Munna Bhai M.B.B.S.,Bollywood,2003,8.1,Vinod Chopra Productions,100.0,410.0,Millions,INR,Hindi

In [ ]:
df[df.release_year.between(2000,2010)]

'''
df[df.release_year.between(2000, 2010)]                       # 2000–2010 inclusive
df[df.release_year.between(2000, 2010, inclusive="neither")]  # 2001–2009
df[df.release_year.between(2000, 2010, inclusive="left")]     # 2000–2009
df[df.release_year.between(2000, 2010, inclusive="right")]    # 2001–2010

'''

,title,industry,release_year,imdb_rating,studio,budget,revenue,unit,currency,language
7,The Pursuit of Happyness,Hollywood,2006,8.0,Columbia Pictures,55.0,307.1,Millions,USD,English
8,Gladiator,Hollywood,2000,8.5,Universal Pictures,103.0,460.5,Millions,USD,English
11,Avatar,Hollywood,2009,7.8,20th Century Fox,237.0,2847.0,Millions,USD,English
13,The Dark Knight,Hollywood,2008,9.0,Syncopy,185.0,1006.0,Millions,USD,English
22,3 Idiots,Bollywood,2009,8.4,Vinod Chopra Films,550.0,4000.0,Millions,INR,Hindi
23,Kabhi Khushi Kabhie Gham,Bollywood,2001,7.4,Dharma Productions,390.0,1360.0,Millions,INR,Hindi
25,Taare Zameen Par,Bollywood,2007,8.3,NaN,120.0,1350.0,Millions,INR,Hindi
26,Munna Bhai M.B.B.S.,Bollywood,2003,8.1,Vinod Chopra Productions,100.0,410.0,Millions,INR,Hindi

In [45]:
df[df.imdb_rating.between(1,7)]

,title,industry,release_year,imdb_rating,studio,budget,revenue,unit,currency,language
1,Doctor Strange in the Multiverse of Madness,Hollywood,2022,7.0,Marvel Studios,200.0,954.8,Millions,USD,English
2,Thor: The Dark World,Hollywood,2013,6.8,Marvel Studios,165.0,644.8,Millions,USD,English
4,Thor: Love and Thunder,Hollywood,2022,6.8,Marvel Studios,250.0,670.0,Millions,USD,English
19,Captain America: The First Avenger,Hollywood,2011,6.9,Marvel Studios,216.7,370.6,Millions,USD,English
31,Race 3,Bollywood,2018,1.9,Salman Khan Films,1.8,3.1,Billions,INR,Hindi

In [46]:
df.studio.unique()

<StringArray>
['Government of West Bengal',            'Marvel Studios',
 'Castle Rock Entertainment',     'Warner Bros. Pictures',
         'Columbia Pictures',      'Universal Pictures  ',
        'Paramount Pictures',             'Liberty Films',
          '20th Century Fox',                   'Syncopy',
        'Universal Pictures',                         nan,
            'Yash Raj Films',        'Vinod Chopra Films',
        'Dharma Productions',  'Vinod Chopra Productions',
               'Zee Studios',         'Salman Khan Films',
             'Hombale Films',       'Mythri Movie Makers',
         'DVV Entertainment',          'Arka Media Works']
Length: 22, dtype: str

In [49]:
df[df.studio=="Marvel Studios"]

,title,industry,release_year,imdb_rating,studio,budget,revenue,unit,currency,language
1,Doctor Strange in the Multiverse of Madness,Hollywood,2022,7.0,Marvel Studios,200.0,954.8,Millions,USD,English
2,Thor: The Dark World,Hollywood,2013,6.8,Marvel Studios,165.0,644.8,Millions,USD,English
3,Thor: Ragnarok,Hollywood,2017,7.9,Marvel Studios,180.0,854.0,Millions,USD,English
4,Thor: Love and Thunder,Hollywood,2022,6.8,Marvel Studios,250.0,670.0,Millions,USD,English
17,Avengers: Endgame,Hollywood,2019,8.4,Marvel Studios,400.0,2798.0,Millions,USD,English
18,Avengers: Infinity War,Hollywood,2018,8.4,Marvel Studios,400.0,2048.0,Millions,USD,English
19,Captain America: The First Avenger,Hollywood,2011,6.9,Marvel Studios,216.7,370.6,Millions,USD,English
20,Captain America: The Winter Soldier,Hollywood,2014,7.8,Marvel Studios,177.0,714.4,Millions,USD,English

In [50]:
df.describe()

       release_year  imdb_rating        budget        revenue
count     37.000000    36.000000     37.000000      37.000000
mean    2007.027027     7.919444   2084.975135    4117.135135
std       17.657995     1.204947  11477.487145   16372.462682
min     1946.000000     1.900000      1.000000       3.100000
25%     2001.000000     7.800000     15.500000     263.100000
50%     2014.000000     8.100000    165.000000     701.800000
75%     2018.000000     8.400000    250.000000    2000.000000
max     2022.000000     9.300000  70000.000000  100000.000000

In [51]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 37 entries, 0 to 36
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   title         37 non-null     str
 1   industry      37 non-null     str
 2   release_year  37 non-null     int64
 3   imdb_rating   36 non-null     float64
 4   studio        34 non-null     str
 5   budget        37 non-null     float64
 6   revenue       37 non-null     float64
 7   unit          37 non-null     str
 8   currency      37 non-null     str
 9   language      37 non-null     str
dtypes: float64(3), int64(1), str(6)
memory usage: 3.0 KB

In [52]:
df[df.imdb_rating==df.imdb_rating.max()]

,title,industry,release_year,imdb_rating,studio,budget,revenue,unit,currency,language
5,The Shawshank Redemption,Hollywood,1994,9.3,Castle Rock Entertainment,25.0,73.3,Millions,USD,English

In [53]:
df[df.imdb_rating==df.imdb_rating.min()]

,title,industry,release_year,imdb_rating,studio,budget,revenue,unit,currency,language
31,Race 3,Bollywood,2018,1.9,Salman Khan Films,1.8,3.1,Billions,INR,Hindi

In [55]:
df[(df.imdb_rating==df.imdb_rating.max()) | (df.imdb_rating==df.imdb_rating.min())]

,title,industry,release_year,imdb_rating,studio,budget,revenue,unit,currency,language
5,The Shawshank Redemption,Hollywood,1994,9.3,Castle Rock Entertainment,25.0,73.3,Millions,USD,English
31,Race 3,Bollywood,2018,1.9,Salman Khan Films,1.8,3.1,Billions,INR,Hindi

In [56]:
from datetime import datetime

current_year = datetime.now().year

df["age"] = df["release_year"].apply(lambda x : current_year - x )

df.head(4)

,title,industry,release_year,imdb_rating,studio,budget,revenue,unit,currency,language,age
0,Pather Panchali,Bollywood,1955,8.3,Government of West Bengal,70000.0,100000.0,Thousands,INR,Bengali,71
1,Doctor Strange in the Multiverse of Madness,Hollywood,2022,7.0,Marvel Studios,200.0,954.8,Millions,USD,English,4
2,Thor: The Dark World,Hollywood,2013,6.8,Marvel Studios,165.0,644.8,Millions,USD,English,13
3,Thor: Ragnarok,Hollywood,2017,7.9,Marvel Studios,180.0,854.0,Millions,USD,English,9

In [59]:
df["profit"]=df.apply(lambda x: x['revenue'] - x['budget'],axis=1)

In [60]:
df.head(4)

,title,industry,release_year,imdb_rating,studio,budget,revenue,unit,currency,language,age,profit
0,Pather Panchali,Bollywood,1955,8.3,Government of West Bengal,70000.0,100000.0,Thousands,INR,Bengali,71,30000.0
1,Doctor Strange in the Multiverse of Madness,Hollywood,2022,7.0,Marvel Studios,200.0,954.8,Millions,USD,English,4,754.8
2,Thor: The Dark World,Hollywood,2013,6.8,Marvel Studios,165.0,644.8,Millions,USD,English,13,479.8
3,Thor: Ragnarok,Hollywood,2017,7.9,Marvel Studios,180.0,854.0,Millions,USD,English,9,674.0

In [61]:
df.index

RangeIndex(start=0, stop=37, step=1)

In [62]:
df.loc[0]

title                     Pather Panchali
industry                        Bollywood
release_year                         1955
imdb_rating                           8.3
studio          Government of West Bengal
budget                            70000.0
revenue                          100000.0
unit                            Thousands
currency                              INR
language                          Bengali
age                                    71
profit                            30000.0
Name: 0, dtype: object

In [63]:
df.set_index("title",inplace=True) #Inplace will change the exsisting datafram and if user is not using inplace then has to save in new dataframe
df.head(3)

,industry,release_year,imdb_rating,studio,budget,revenue,unit,currency,language,age,profit
title,,,,,,,,,,,
Pather Panchali,Bollywood,1955,8.3,Government of West Bengal,70000.0,100000.0,Thousands,INR,Bengali,71,30000.0
Doctor Strange in the Multiverse of Madness,Hollywood,2022,7.0,Marvel Studios,200.0,954.8,Millions,USD,English,4,754.8
Thor: The Dark World,Hollywood,2013,6.8,Marvel Studios,165.0,644.8,Millions,USD,English,13,479.8

In [ ]:
df.loc["Pather Panchali"]

industry                        Bollywood
release_year                         1955
imdb_rating                           8.3
studio          Government of West Bengal
budget                            70000.0
revenue                          100000.0
unit                            Thousands
currency                              INR
language                          Bengali
age                                    71
profit                            30000.0
Name: Pather Panchali, dtype: object

In [70]:
df.loc[["Pather Panchali","Thor: The Dark World "]]

,industry,release_year,imdb_rating,studio,budget,revenue,unit,currency,language,age,profit
title,,,,,,,,,,,
Pather Panchali,Bollywood,1955,8.3,Government of West Bengal,70000.0,100000.0,Thousands,INR,Bengali,71,30000.0
Thor: The Dark World,Hollywood,2013,6.8,Marvel Studios,165.0,644.8,Millions,USD,English,13,479.8

In [71]:
df.iloc[0]

industry                        Bollywood
release_year                         1955
imdb_rating                           8.3
studio          Government of West Bengal
budget                            70000.0
revenue                          100000.0
unit                            Thousands
currency                              INR
language                          Bengali
age                                    71
profit                            30000.0
Name: Pather Panchali, dtype: object

In [72]:
df.iloc[2:5]

,industry,release_year,imdb_rating,studio,budget,revenue,unit,currency,language,age,profit
title,,,,,,,,,,,
Thor: The Dark World,Hollywood,2013,6.8,Marvel Studios,165.0,644.8,Millions,USD,English,13,479.8
Thor: Ragnarok,Hollywood,2017,7.9,Marvel Studios,180.0,854.0,Millions,USD,English,9,674.0
Thor: Love and Thunder,Hollywood,2022,6.8,Marvel Studios,250.0,670.0,Millions,USD,English,4,420.0

In [73]:
df.reset_index(inplace=True)

In [74]:
df

,title,industry,release_year,imdb_rating,studio,budget,revenue,unit,currency,language,age,profit
0,Pather Panchali,Bollywood,1955,8.3,Government of West Bengal,70000.00,100000.0,Thousands,INR,Bengali,71,30000.00
1,Doctor Strange in the Multiverse of Madness,Hollywood,2022,7.0,Marvel Studios,200.00,954.8,Millions,USD,English,4,754.80
2,Thor: The Dark World,Hollywood,2013,6.8,Marvel Studios,165.00,644.8,Millions,USD,English,13,479.80
3,Thor: Ragnarok,Hollywood,2017,7.9,Marvel Studios,180.00,854.0,Millions,USD,English,9,674.00
4,Thor: Love and Thunder,Hollywood,2022,6.8,Marvel Studios,250.00,670.0,Millions,USD,English,4,420.00
5,The Shawshank Redemption,Hollywood,1994,9.3,Castle Rock Entertainment,25.00,73.3,Millions,USD,English,32,48.30
6,Interstellar,Hollywood,2014,8.6,Warner Bros. Pictures,165.00,701.8,Millions,USD,English,12,536.80
7,The Pursuit of Happyness,Hollywood,2006,8.0,Columbia Pictures,55.00,307.1,Millions,USD,English,20,252.10
8,Gladiator,Hollywood,2000,8.5,Universal Pictures,103.00,460.5,Millions,USD,English,26,357.50
9,Titanic,Hollywood,1997,7.9,Paramount Pictures,200.00,2202.0,Millions,USD,English,29,2002.00
10,It's a Wonderful Life,Hollywood,1946,8.6,Liberty Films,3.18,3.3,Millions,USD,English,80,0.12
11,Avatar,Hollywood,2009,7.8,20th Century Fox,237.00,2847.0,Millions,USD,English,17,2610.00
12,The Godfather,Hollywood,1972,9.2,Paramount Pictures,7.20,291.0,Millions,USD,English,54,283.80
13,The Dark Knight,Hollywood,2008,9.0,Syncopy,185.00,1006.0,Millions,USD,English,18,821.00
14,Schindler's List,Hollywood,1993,9.0,Universal Pictures,22.00,322.2,Millions,USD,English,33,300.20
15,Jurassic Park,Hollywood,1993,8.2,Universal Pictures,63.00,1046.0,Millions,USD,English,33,983.00
16,Parasite,Hollywood,2019,8.5,NaN,15.50,263.1,Millions,USD,English,7,247.60
17,Avengers: Endgame,Hollywood,2019,8.4,Marvel Studios,400.00,2798.0,Millions,USD,English,7,2398.00
18,Avengers: Infinity War,Hollywood,2018,8.4,Marvel Studios,400.00,2048.0,Millions,USD,English,8,1648.00
19,Captain America: The First Avenger,Hollywood,2011,6.9,Marvel Studios,216.70,370.6,Millions,USD,English,15,153.90
20,Captain America: The Winter Soldier,Hollywood,2014,7.8,Marvel Studios,177.00,714.4,Millions,USD,English,12,537.40
21,Dilwale Dulhania Le Jayenge,Bollywood,1995,8.0,Yash Raj Films,400.00,2000.0,Millions,INR,Hindi,31,1600.00
22,3 Idiots,Bollywood,2009,8.4,Vinod Chopra Films,550.00,4000.0,Millions,INR,Hindi,17,3450.00
23,Kabhi Khushi Kabhie Gham,Bollywood,2001,7.4,Dharma Productions,390.00,1360.0,Millions,INR,Hindi,25,970.00
24,Bajirao Mastani,Bollywood,2015,7.2,NaN,1.40,3.5,Billions,INR,Hindi,11,2.10
25,Taare Zameen Par,Bollywood,2007,8.3,NaN,120.00,1350.0,Millions,INR,Hindi,19,1230.00
26,Munna Bhai M.B.B.S.,Bollywood,2003,8.1,Vinod Chopra Productions,100.00,410.0,Millions,INR,Hindi,23,310.00
27,PK,Bollywood,2014,8.1,Vinod Chopra Films,850.00,8540.0,Millions,INR,Hindi,12,7690.00
28,Sanju,Bollywood,2018,NaN,Vinod Chopra Films,1.00,5.9,Billions,INR,Hindi,8,4.90
29,The Kashmir Files,Bollywood,2022,8.3,Zee Studios,250.00,3409.0,Millions,INR,Hindi,4,3159.00
30,Bajrangi Bhaijaan,Bollywood,2015,8.1,Salman Khan Films,900.00,11690.0,Millions,INR,Hindi,11,10790.00
31,Race 3,Bollywood,2018,1.9,Salman Khan Films,1.80,3.1,Billions,INR,Hindi,8,1.30
32,Shershaah,Bollywood,2021,8.4,Dharma Productions,500.00,950.0,Millions,INR,Hindi,5,450.00
33,K.G.F: Chapter 2,Bollywood,2022,8.4,Hombale Films,1.00,12.5,Billions,INR,Kannada,4,11.50
34,Pushpa: The Rise - Part 1,Bollywood,2021,7.6,Mythri Movie Makers,2.00,3.6,Billions,INR,Telugu,5,1.60
35,RRR,Bollywood,2022,8.0,DVV Entertainment,5.50,12.0,Billions,INR,Telugu,4,6.50
36,Baahubali: The Beginning,Bollywood,2015,8.0,Arka Media Works,1.80,6.5,Billions,INR,Telugu,11,4.70