In [ ]:
import pandas as pd
df=pd.read_csv("stock_data.csv")

In [3]:
df

,Datasource: Google finance,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4
0,tickers,eps,revenue,price,people
1,GOOGL,27.82,87,845,larry page
2,WMT,4.61,484,65,n.a.
3,MSFT,-1,85,64,bill gates
4,RIL,not available,50,1023,mukesh ambani
5,TATA,5.6,-1,n.a.,ratan tata

In [11]:
df=pd.read_csv("stock_data.csv",skiprows=1)
df

  tickers            eps  revenue price         people
0   GOOGL          27.82       87   845     larry page
1     WMT           4.61      484    65           n.a.
2    MSFT             -1       85    64     bill gates
3    RIL   not available       50  1023  mukesh ambani
4    TATA            5.6       -1  n.a.     ratan tata

In [12]:
df=pd.read_csv("stock_data.csv",header=1)
df

  tickers            eps  revenue price         people
0   GOOGL          27.82       87   845     larry page
1     WMT           4.61      484    65           n.a.
2    MSFT             -1       85    64     bill gates
3    RIL   not available       50  1023  mukesh ambani
4    TATA            5.6       -1  n.a.     ratan tata

In [13]:
df=pd.read_csv("stock_data.csv",header=1,names=["stock_symbol","Earning/share","Revenue","Stock_price","People"])
df

  stock_symbol  Earning/share  Revenue Stock_price         People
0        GOOGL          27.82       87         845     larry page
1          WMT           4.61      484          65           n.a.
2         MSFT             -1       85          64     bill gates
3         RIL   not available       50        1023  mukesh ambani
4         TATA            5.6       -1        n.a.     ratan tata

In [16]:
df=pd.read_csv("stock_data.csv",header=1,nrows=4)
df

  tickers            eps  revenue  price         people
0   GOOGL          27.82       87    845     larry page
1     WMT           4.61      484     65           n.a.
2    MSFT             -1       85     64     bill gates
3    RIL   not available       50   1023  mukesh ambani

In [20]:
df=pd.read_csv("stock_data.csv",header=1, na_values={
    'eps':['not available'],
    'revenue':[-1],
    'price':['n.a.']
})

df

  tickers    eps  revenue   price         people
0   GOOGL  27.82     87.0   845.0     larry page
1     WMT   4.61    484.0    65.0           n.a.
2    MSFT  -1.00     85.0    64.0     bill gates
3    RIL     NaN     50.0  1023.0  mukesh ambani
4    TATA   5.60      NaN     NaN     ratan tata

In [21]:
df=pd.read_csv("stock_data.csv",header=1, na_values=['not available',-1,'n.a.'])  #all value in the list will become null, but above implementation is correct
df

  tickers    eps  revenue   price         people
0   GOOGL  27.82     87.0   845.0     larry page
1     WMT   4.61    484.0    65.0            NaN
2    MSFT    NaN     85.0    64.0     bill gates
3    RIL     NaN     50.0  1023.0  mukesh ambani
4    TATA   5.60      NaN     NaN     ratan tata

In [32]:
df=pd.read_csv("stock_data.csv",header=1, na_values={
    'eps':['not available',-1],
    'revenue':[-1],
    'price':['n.a.'],
    
})

df

  tickers    eps  revenue   price         people
0   GOOGL  27.82     87.0   845.0     larry page
1     WMT   4.61    484.0    65.0           n.a.
2    MSFT    NaN     85.0    64.0     bill gates
3    RIL     NaN     50.0  1023.0  mukesh ambani
4    TATA   5.60      NaN     NaN     ratan tata

In [33]:
df["pe"]=df["price"]/df["eps"]    # before doing divition make sure all string object as notavailable or changed to NaN
df

  tickers    eps  revenue   price         people         pe
0   GOOGL  27.82     87.0   845.0     larry page  30.373832
1     WMT   4.61    484.0    65.0           n.a.  14.099783
2    MSFT    NaN     85.0    64.0     bill gates        NaN
3    RIL     NaN     50.0  1023.0  mukesh ambani        NaN
4    TATA   5.60      NaN     NaN     ratan tata        NaN

In [34]:
df.to_csv("pe.csv")

In [35]:
df.to_csv("pe1.csv",index=False)

In [ ]:
df_movies=pd.read_excel("movies_db.xlsx","movies")
df_movies.head(4)

,movie_id,title,industry,release_year,imdb_rating,studio,language_id
0,101,K.G.F: Chapter 2,Bollywood,2022,8.4,Hombale Films,3
1,102,Doctor Strange in the Multiverse of Madness,Hollywood,2022,7.0,Marvel Studios,5
2,103,Thor: The Dark World,Hollywood,2013,6.8,Marvel Studios,5
3,104,Thor: Ragnarok,Hollywood,2017,7.9,Marvel Studios,5

In [39]:
df_financials=pd.read_excel("movies_db.xlsx","financials")
df_financials.head(4)

   movie_id  budget  revenue      unit currency
0       101     1.0     12.5  Billions      INR
1       102   200.0    954.8  Millions      USD
2       103   165.0    644.8  Millions       $$
3       104   180.0    854.0  Millions  Dollars

In [40]:
df_financials["currency"].unique()

<StringArray>
['INR', 'USD', '$$', 'Dollars']
Length: 4, dtype: str

In [42]:
def standardize_currency(curr):
    if curr == '$$' or curr == "Dollars":
        return "USD"
    return curr



df_financials=pd.read_excel("movies_db.xlsx","financials",converters={
    "currency": standardize_currency

})
df_financials.head(4)

   movie_id  budget  revenue      unit currency
0       101     1.0     12.5  Billions      INR
1       102   200.0    954.8  Millions      USD
2       103   165.0    644.8  Millions      USD
3       104   180.0    854.0  Millions      USD

In [43]:
df_merge=pd.merge(df_movies,df_financials, on="movie_id")
df_merge.head(4)

,movie_id,title,industry,release_year,imdb_rating,studio,language_id,budget,revenue,unit,currency
0,101,K.G.F: Chapter 2,Bollywood,2022,8.4,Hombale Films,3,1.0,12.5,Billions,INR
1,102,Doctor Strange in the Multiverse of Madness,Hollywood,2022,7.0,Marvel Studios,5,200.0,954.8,Millions,USD
2,103,Thor: The Dark World,Hollywood,2013,6.8,Marvel Studios,5,165.0,644.8,Millions,USD
3,104,Thor: Ragnarok,Hollywood,2017,7.9,Marvel Studios,5,180.0,854.0,Millions,USD

In [44]:
df_merge.to_excel("movies_merged1.xlsx",sheet_name="Movies_fin",index=False)

In [47]:
df_stocks=pd.DataFrame({
    'tickers':['Google','WMT','MSFT'],
    'price':[345,432,426],
    'P/E':[23,21.45,20.05],
    'eps':['NAN',45,34]
})
df_stocks

  tickers  price    P/E  eps
0  Google    345  23.00  NAN
1     WMT    432  21.45   45
2    MSFT    426  20.05   34

In [48]:
df_weather = pd.DataFrame({
    'day':['1/1/2017','1/2/2017','1/3/2017'],
    'tempeature':[44,32,12],
    'event':['sunny','Rain','snow']
})

df_weather

        day  tempeature  event
0  1/1/2017          44  sunny
1  1/2/2017          32   Rain
2  1/3/2017          12   snow

In [49]:
with pd.ExcelWriter("stock_weather.xlsx") as writer:
    df_stocks.to_excel(writer,sheet_name="Stocks")
    df_weather.to_excel(writer,sheet_name="weather")

In [123]:
df_w=pd.read_csv("weather_data.csv")
df_w

        day  temperature  windspeed     event
0  1/1/2017           32          6      Rain
1  1/2/2017       -99999          7     Sunny
2  1/3/2017           28     -99999      Snow
3  1/4/2017       -99999          7  no event
4  1/5/2017           32     -99999      Rain
5  1/6/2017           31          2     Sunny
6  1/6/2017           34     -88888  no event

In [51]:
df_w=df_w.mask(df_w < 0, np.nan)
df_w

TypeError: '<' not supported between instances of 'str' and 'int'

In [116]:
numeric_cols = df_w.select_dtypes(include="number").columns
print(numeric_cols)

Index(['temperature', 'windspeed'], dtype='str')

In [63]:
df_w

        day  temperature  windspeed     event
0  1/1/2017           32          6      Rain
1  1/2/2017       -99999          7     Sunny
2  1/3/2017           28     -99999      Snow
3  1/4/2017       -99999          7  no event
4  1/5/2017           32     -99999      Rain
5  1/6/2017           31          2     Sunny
6  1/6/2017           34     -88888  no event

In [124]:
import numpy as np
df_w[['temperature','windspeed']] = df_w[['temperature','windspeed']].mask(df_w[['temperature','windspeed']] < 0, np.nan)

In [125]:
df_w

        day  temperature  windspeed     event
0  1/1/2017         32.0        6.0      Rain
1  1/2/2017          NaN        7.0     Sunny
2  1/3/2017         28.0        NaN      Snow
3  1/4/2017          NaN        7.0  no event
4  1/5/2017         32.0        NaN      Rain
5  1/6/2017         31.0        2.0     Sunny
6  1/6/2017         34.0        NaN  no event

In [81]:
type(df_w.day[0])

str

In [82]:
df_w["day"] = pd.to_datetime(df_w["day"])

In [83]:
type(df_w.day[0])

pandas.Timestamp

In [84]:
df_w

         day  temperature  windspeed     event
0 2017-01-01         32.0        6.0      Rain
1 2017-01-02          NaN        7.0     Sunny
2 2017-01-03         28.0        NaN      Snow
3 2017-01-04          NaN        7.0  no event
4 2017-01-05         32.0        NaN      Rain
5 2017-01-06         31.0        2.0     Sunny
6 2017-01-06         34.0        NaN  no event

In [85]:
df_w["day"][0].strftime("%d-%m-%Y")

'01-01-2017'

In [86]:
df_w

         day  temperature  windspeed     event
0 2017-01-01         32.0        6.0      Rain
1 2017-01-02          NaN        7.0     Sunny
2 2017-01-03         28.0        NaN      Snow
3 2017-01-04          NaN        7.0  no event
4 2017-01-05         32.0        NaN      Rain
5 2017-01-06         31.0        2.0     Sunny
6 2017-01-06         34.0        NaN  no event

In [87]:
df_w["day"] = df_w["day"].dt.strftime("%d-%m-%Y")
df_w

          day  temperature  windspeed     event
0  01-01-2017         32.0        6.0      Rain
1  02-01-2017          NaN        7.0     Sunny
2  03-01-2017         28.0        NaN      Snow
3  04-01-2017          NaN        7.0  no event
4  05-01-2017         32.0        NaN      Rain
5  06-01-2017         31.0        2.0     Sunny
6  06-01-2017         34.0        NaN  no event

In [89]:
df_n=df_w.fillna(0)
df_n

          day  temperature  windspeed     event
0  01-01-2017         32.0        6.0      Rain
1  02-01-2017          0.0        7.0     Sunny
2  03-01-2017         28.0        0.0      Snow
3  04-01-2017          0.0        7.0  no event
4  05-01-2017         32.0        0.0      Rain
5  06-01-2017         31.0        2.0     Sunny
6  06-01-2017         34.0        0.0  no event

In [90]:
df_w

          day  temperature  windspeed     event
0  01-01-2017         32.0        6.0      Rain
1  02-01-2017          NaN        7.0     Sunny
2  03-01-2017         28.0        NaN      Snow
3  04-01-2017          NaN        7.0  no event
4  05-01-2017         32.0        NaN      Rain
5  06-01-2017         31.0        2.0     Sunny
6  06-01-2017         34.0        NaN  no event

In [99]:
df_w.fillna({
    'temperature':df_w.temperature.mean(),
    #'windspeed':df_w.windspeed.mode()[0],
    'windspeed':df_w.windspeed.median(),
    'event':'No Event'

})

          day  temperature  windspeed     event
0  01-01-2017         32.0        6.0      Rain
1  02-01-2017         31.4        7.0     Sunny
2  03-01-2017         28.0        6.5      Snow
3  04-01-2017         31.4        7.0  no event
4  05-01-2017         32.0        6.5      Rain
5  06-01-2017         31.0        2.0     Sunny
6  06-01-2017         34.0        6.5  no event

In [100]:
df_w.fillna(method='ffill')

TypeError: NDFrame.fillna() got an unexpected keyword argument 'method'

In [101]:
df_w.ffill()

          day  temperature  windspeed     event
0  01-01-2017         32.0        6.0      Rain
1  02-01-2017         32.0        7.0     Sunny
2  03-01-2017         28.0        7.0      Snow
3  04-01-2017         28.0        7.0  no event
4  05-01-2017         32.0        7.0      Rain
5  06-01-2017         31.0        2.0     Sunny
6  06-01-2017         34.0        2.0  no event

In [103]:
df_w.bfill()

          day  temperature  windspeed     event
0  01-01-2017         32.0        6.0      Rain
1  02-01-2017         28.0        7.0     Sunny
2  03-01-2017         28.0        7.0      Snow
3  04-01-2017         32.0        7.0  no event
4  05-01-2017         32.0        2.0      Rain
5  06-01-2017         31.0        2.0     Sunny
6  06-01-2017         34.0        NaN  no event

In [104]:
df_w.bfill(axis=1)

          day temperature windspeed     event
0  01-01-2017        32.0       6.0      Rain
1  02-01-2017         7.0       7.0     Sunny
2  03-01-2017        28.0      Snow      Snow
3  04-01-2017         7.0       7.0  no event
4  05-01-2017        32.0      Rain      Rain
5  06-01-2017        31.0       2.0     Sunny
6  06-01-2017        34.0  no event  no event

In [106]:
df_w

          day  temperature  windspeed     event
0  01-01-2017         32.0        6.0      Rain
1  02-01-2017          NaN        7.0     Sunny
2  03-01-2017         28.0        NaN      Snow
3  04-01-2017          NaN        7.0  no event
4  05-01-2017         32.0        NaN      Rain
5  06-01-2017         31.0        2.0     Sunny
6  06-01-2017         34.0        NaN  no event

In [107]:
df_w.ffill(limit=1)

          day  temperature  windspeed     event
0  01-01-2017         32.0        6.0      Rain
1  02-01-2017         32.0        7.0     Sunny
2  03-01-2017         28.0        7.0      Snow
3  04-01-2017         28.0        7.0  no event
4  05-01-2017         32.0        7.0      Rain
5  06-01-2017         31.0        2.0     Sunny
6  06-01-2017         34.0        2.0  no event

In [110]:
df_w.interpolate()

TypeError: Cannot interpolate with str dtype

In [111]:
df_w[["windspeed","temperature"]].interpolate()

   windspeed  temperature
0        6.0         32.0
1        7.0         30.0
2        7.0         28.0
3        7.0         30.0
4        4.5         32.0
5        2.0         31.0
6        2.0         34.0

In [ ]:
df_w[["windspeed", "temperature"]] = (
    df_w[["windspeed", "temperature"]].interpolate()
)

print(df_w)

## this will affect orginal dataframe

        day  temperature  windspeed     event
0  1/1/2017         32.0        6.0      Rain
1  1/2/2017         30.0        7.0     Sunny
2  1/3/2017         28.0        7.0      Snow
3  1/4/2017         30.0        7.0  no event
4  1/5/2017         32.0        4.5      Rain
5  1/6/2017         31.0        2.0     Sunny
6  1/6/2017         34.0        2.0  no event

In [ ]:
#to avoid originally aftected data frame 
preview = df_w.assign(
    temperature=df_w["temperature"].interpolate(),
    windspeed=df_w["windspeed"].interpolate()
)

print(preview)

# just creating another data frome and assigned

        day  temperature  windspeed     event
0  1/1/2017         32.0        6.0      Rain
1  1/2/2017         30.0        7.0     Sunny
2  1/3/2017         28.0        7.0      Snow
3  1/4/2017         30.0        7.0  no event
4  1/5/2017         32.0        4.5      Rain
5  1/6/2017         31.0        2.0     Sunny
6  1/6/2017         34.0        2.0  no event

In [128]:
df_w   # created again the df_w and drop na

        day  temperature  windspeed     event
0  1/1/2017         32.0        6.0      Rain
1  1/2/2017          NaN        7.0     Sunny
2  1/3/2017         28.0        NaN      Snow
3  1/4/2017          NaN        7.0  no event
4  1/5/2017         32.0        NaN      Rain
5  1/6/2017         31.0        2.0     Sunny
6  1/6/2017         34.0        NaN  no event

In [ ]:
df_w.dropna() ##dropna(it is equal to dropna(how="any"))

        day  temperature  windspeed  event
0  1/1/2017         32.0        6.0   Rain
5  1/6/2017         31.0        2.0  Sunny

In [131]:
df_w.dropna(how="all")

        day  temperature  windspeed     event
0  1/1/2017         32.0        6.0      Rain
1  1/2/2017          NaN        7.0     Sunny
2  1/3/2017         28.0        NaN      Snow
3  1/4/2017          NaN        7.0  no event
4  1/5/2017         32.0        NaN      Rain
5  1/6/2017         31.0        2.0     Sunny
6  1/6/2017         34.0        NaN  no event

        day  temperature  windspeed     event
0  1/1/2017         32.0        6.0      Rain
1  1/2/2017          NaN        7.0     Sunny
2  1/3/2017         28.0        NaN      Snow
3  1/4/2017          NaN        7.0  no event
4  1/5/2017         32.0        NaN      Rain
5  1/6/2017         31.0        2.0     Sunny
6  1/6/2017         34.0        NaN  no event

In [133]:
numeric_cols = df_w.select_dtypes(include="number").columns
print(numeric_cols)

Index(['temperature', 'windspeed'], dtype='str')

In [134]:
df_w=pd.read_csv("weather_data.csv")
df_w

        day  temperature  windspeed     event
0  1/1/2017           32          6      Rain
1  1/2/2017       -99999          7     Sunny
2  1/3/2017           28     -99999      Snow
3  1/4/2017       -99999          7  no event
4  1/5/2017           32     -99999      Rain
5  1/6/2017           31          2     Sunny
6  1/6/2017           34     -88888  no event

In [ ]:
df_w.replace(-99999,'NaN')

        day temperature windspeed     event
0  1/1/2017          32         6      Rain
1  1/2/2017         NaN         7     Sunny
2  1/3/2017          28       NaN      Snow
3  1/4/2017         NaN         7  no event
4  1/5/2017          32       NaN      Rain
5  1/6/2017          31         2     Sunny
6  1/6/2017          34    -88888  no event

In [137]:
df_w.replace(-88888,'NaN')

        day  temperature windspeed     event
0  1/1/2017           32         6      Rain
1  1/2/2017       -99999         7     Sunny
2  1/3/2017           28    -99999      Snow
3  1/4/2017       -99999         7  no event
4  1/5/2017           32    -99999      Rain
5  1/6/2017           31         2     Sunny
6  1/6/2017           34       NaN  no event

In [141]:
df_w.replace([-99999,-88888],'NaN')

        day temperature windspeed     event
0  1/1/2017          32         6      Rain
1  1/2/2017         NaN         7     Sunny
2  1/3/2017          28       NaN      Snow
3  1/4/2017         NaN         7  no event
4  1/5/2017          32       NaN      Rain
5  1/6/2017          31         2     Sunny
6  1/6/2017          34       NaN  no event

In [ ]:
df_w.replace([-99999,-88888],'NaN').isna().sum() # please check NaN is not null, it make it null use above method by using np

day            0
temperature    0
windspeed      0
event          0
dtype: int64

In [143]:
df_w.replace([-99999,-88888],'NaN').isnull().sum()

day            0
temperature    0
windspeed      0
event          0
dtype: int64

In [144]:
df_w

        day  temperature  windspeed     event
0  1/1/2017           32          6      Rain
1  1/2/2017       -99999          7     Sunny
2  1/3/2017           28     -99999      Snow
3  1/4/2017       -99999          7  no event
4  1/5/2017           32     -99999      Rain
5  1/6/2017           31          2     Sunny
6  1/6/2017           34     -88888  no event

In [152]:
df_n=df_w.replace([-99999,-88888],np.nan)

In [153]:
df_n

        day  temperature  windspeed     event
0  1/1/2017         32.0        6.0      Rain
1  1/2/2017          NaN        7.0     Sunny
2  1/3/2017         28.0        NaN      Snow
3  1/4/2017          NaN        7.0  no event
4  1/5/2017         32.0        NaN      Rain
5  1/6/2017         31.0        2.0     Sunny
6  1/6/2017         34.0        NaN  no event

In [154]:
df_n.isnull().sum()

day            0
temperature    2
windspeed      3
event          0
dtype: int64

In [155]:
df_n=df_w.replace(to_replace=[-99999,-88888],value=np.nan) #same as before
df_n

        day  temperature  windspeed     event
0  1/1/2017         32.0        6.0      Rain
1  1/2/2017          NaN        7.0     Sunny
2  1/3/2017         28.0        NaN      Snow
3  1/4/2017          NaN        7.0  no event
4  1/5/2017         32.0        NaN      Rain
5  1/6/2017         31.0        2.0     Sunny
6  1/6/2017         34.0        NaN  no event

In [157]:
df_w.replace({
    -99999: np.nan,
    -88888: np.nan,
    'no event':'Sunny'
})

        day  temperature  windspeed  event
0  1/1/2017         32.0        6.0   Rain
1  1/2/2017          NaN        7.0  Sunny
2  1/3/2017         28.0        NaN   Snow
3  1/4/2017          NaN        7.0  Sunny
4  1/5/2017         32.0        NaN   Rain
5  1/6/2017         31.0        2.0  Sunny
6  1/6/2017         34.0        NaN  Sunny

In [169]:
df_r = pd.DataFrame({
    'Score':['exceptional','good','average','Exceptional','GOOD','gOOD'],
    'Name':['ram','raju','ragav','ramam','ravi','raghu']
})

df_r

         Score   Name
0  exceptional    ram
1         good   raju
2      average  ragav
3  Exceptional  ramam
4         GOOD   ravi
5         gOOD  raghu

In [170]:
df_r["Score"] = (
    df_r["Score"]
    .str.strip()
    .str.title()
)
df_r

         Score   Name
0  Exceptional    ram
1         Good   raju
2      Average  ragav
3  Exceptional  ramam
4         Good   ravi
5         Good  raghu

In [174]:
df_r["Score"] = (
    df_r["Score"]
    .str.strip()
    .str.title()
    .map({
        "exceptional": 1,
        "good": 2,
        "average": 3
    })
)
df_r

#the error is because the above excution has change exceptional to Exceptional already.so this will turn the value to NaN

   Score   Name
0    NaN    ram
1    NaN   raju
2    NaN  ragav
3    NaN  ramam
4    NaN   ravi
5    NaN  raghu

In [171]:
df_r["Score"] = (
    df_r["Score"]
    .str.strip()
    .str.title()
    .map({
        "Exceptional": 1,
        "Good": 2,
        "Average": 3
    })
)
df_r

   Score   Name
0      1    ram
1      2   raju
2      3  ragav
3      1  ramam
4      2   ravi
5      2  raghu

In [175]:
df_r = pd.DataFrame({
    'Score':['exceptional','good','average','Exceptional','GOOD','gOOD'],
    'Name':['ram','raju','ragav','ramam','ravi','raghu']
})

In [176]:
df_r["Score"] = (
    df_r["Score"]
    .str.strip()
    .str.title()
)
df_r

         Score   Name
0  Exceptional    ram
1         Good   raju
2      Average  ragav
3  Exceptional  ramam
4         Good   ravi
5         Good  raghu

In [178]:
df_r.replace(['Poor','Good','Average','Exceptional'],[1,3,2,4])

  Score   Name
0     4    ram
1     3   raju
2     2  ragav
3     4  ramam
4     3   ravi
5     3  raghu

In [1]:
import pandas as pd
df = pd.read_csv('weather_by_cities.csv')

In [2]:
df

         day      city  temperature  windspeed   event
0   1/1/2017  new york           32          6    Rain
1   1/2/2017  new york           36          7   Sunny
2   1/3/2017  new york           28         12    Snow
3   1/4/2017  new york           33          7   Sunny
4   1/1/2017    mumbai           90          5   Sunny
5   1/2/2017    mumbai           85         12     Fog
6   1/3/2017    mumbai           87         15     Fog
7   1/4/2017    mumbai           92          5    Rain
8   1/1/2017     paris           45         20   Sunny
9   1/2/2017     paris           50         13  Cloudy
10  1/3/2017     paris           54          8  Cloudy
11  1/4/2017     paris           42         10  Cloudy

In [3]:
df[df.city=="new york"]

        day      city  temperature  windspeed  event
0  1/1/2017  new york           32          6   Rain
1  1/2/2017  new york           36          7  Sunny
2  1/3/2017  new york           28         12   Snow
3  1/4/2017  new york           33          7  Sunny

In [3]:
df[df.city=="new york"].temperature.max()

np.int64(36)

In [4]:
g = df.groupby("city")
g

In [5]:
for city,data in g:
    print("city:",city)
    print("\n")
    print("data:", data)

city: mumbai


data:         day    city  temperature  windspeed  event
4  1/1/2017  mumbai           90          5  Sunny
5  1/2/2017  mumbai           85         12    Fog
6  1/3/2017  mumbai           87         15    Fog
7  1/4/2017  mumbai           92          5   Rain
city: new york


data:         day      city  temperature  windspeed  event
0  1/1/2017  new york           32          6   Rain
1  1/2/2017  new york           36          7  Sunny
2  1/3/2017  new york           28         12   Snow
3  1/4/2017  new york           33          7  Sunny
city: paris


data:          day   city  temperature  windspeed   event
8   1/1/2017  paris           45         20   Sunny
9   1/2/2017  paris           50         13  Cloudy
10  1/3/2017  paris           54          8  Cloudy
11  1/4/2017  paris           42         10  Cloudy

In [6]:
for city,data in g:
    print("city:",city)
    print("max:", data.temperature.max())
    print("\n")

city: mumbai
max: 92


city: new york
max: 36


city: paris
max: 54

In [9]:
import pandas as pd
df = pd.read_csv('weather_by_cities.csv')

h = df.groupby("event")
for event,data in h:
    print("event:",event)
    print("\n")
    print("data:", data)
    print("\n")

event: Cloudy


data:          day   city  temperature  windspeed   event
9   1/2/2017  paris           50         13  Cloudy
10  1/3/2017  paris           54          8  Cloudy
11  1/4/2017  paris           42         10  Cloudy


event: Fog


data:         day    city  temperature  windspeed event
5  1/2/2017  mumbai           85         12   Fog
6  1/3/2017  mumbai           87         15   Fog


event: Rain


data:         day      city  temperature  windspeed event
0  1/1/2017  new york           32          6  Rain
7  1/4/2017    mumbai           92          5  Rain


event: Snow


data:         day      city  temperature  windspeed event
2  1/3/2017  new york           28         12  Snow


event: Sunny


data:         day      city  temperature  windspeed  event
1  1/2/2017  new york           36          7  Sunny
3  1/4/2017  new york           33          7  Sunny
4  1/1/2017    mumbai           90          5  Sunny
8  1/1/2017     paris           45         20  Sunny

In [10]:
h.get_group("Sunny")

        day      city  temperature  windspeed  event
1  1/2/2017  new york           36          7  Sunny
3  1/4/2017  new york           33          7  Sunny
4  1/1/2017    mumbai           90          5  Sunny
8  1/1/2017     paris           45         20  Sunny

In [11]:
g.get_group("mumbai")

        day    city  temperature  windspeed  event
4  1/1/2017  mumbai           90          5  Sunny
5  1/2/2017  mumbai           85         12    Fog
6  1/3/2017  mumbai           87         15    Fog
7  1/4/2017  mumbai           92          5   Rain

In [ ]:
h.max() # this is deceiving as windspeed is also giving max value. 
        # the maximum temperature is 92 for rain and it is in mumbai and max windspeed is 6 for newyork
        # this is a wrong df

             day      city  temperature  windspeed
event
Cloudy  1/4/2017     paris           54         13
Fog     1/3/2017    mumbai           87         15
Rain    1/4/2017  new york           92          6
Snow    1/3/2017  new york           28         12
Sunny   1/4/2017     paris           90         20

In [20]:
df.groupby("event")["temperature"].max()

event
Cloudy    54
Fog       87
Rain      92
Snow      28
Sunny     90
Name: temperature, dtype: int64

In [21]:
df.groupby("event")[["temperature"]].max()

        temperature
event
Cloudy           54
Fog              87
Rain             92
Snow             28
Sunny            90

In [22]:
df.loc[df.groupby("event")["temperature"].idxmax()]

         day      city  temperature  windspeed   event
10  1/3/2017     paris           54          8  Cloudy
6   1/3/2017    mumbai           87         15     Fog
7   1/4/2017    mumbai           92          5    Rain
2   1/3/2017  new york           28         12    Snow
4   1/1/2017    mumbai           90          5   Sunny

In [13]:
g.describe()

         temperature                                                   \
               count   mean       std   min    25%   50%    75%   max
city
mumbai           4.0  88.50  3.109126  85.0  86.50  88.5  90.50  92.0
new york         4.0  32.25  3.304038  28.0  31.00  32.5  33.75  36.0
paris            4.0  47.75  5.315073  42.0  44.25  47.5  51.00  54.0

         windspeed
             count   mean       std  min   25%   50%    75%   max
city
mumbai         4.0   9.25  5.057997  5.0  5.00   8.5  12.75  15.0
new york       4.0   8.00  2.708013  6.0  6.75   7.0   8.25  12.0
paris          4.0  12.75  5.251984  8.0  9.50  11.5  14.75  20.0

In [14]:
g.size()

city
mumbai      4
new york    4
paris       4
dtype: int64

In [15]:
def grouper(df,idx,col):
    if 80<= df[col].loc[idx] <=90:
        return '80-90'
    elif 50<=df[col].loc[idx] <=60:
        return '50-60'
    else: 
        return 'others'

In [18]:
o=df.groupby(lambda idx: grouper(df,idx,'temperature'))
o

In [19]:
for key, d in o:
    print("key: ", key)
    print("data:",d)

key:  50-60
data:          day   city  temperature  windspeed   event
9   1/2/2017  paris           50         13  Cloudy
10  1/3/2017  paris           54          8  Cloudy
key:  80-90
data:         day    city  temperature  windspeed  event
4  1/1/2017  mumbai           90          5  Sunny
5  1/2/2017  mumbai           85         12    Fog
6  1/3/2017  mumbai           87         15    Fog
key:  others
data:          day      city  temperature  windspeed   event
0   1/1/2017  new york           32          6    Rain
1   1/2/2017  new york           36          7   Sunny
2   1/3/2017  new york           28         12    Snow
3   1/4/2017  new york           33          7   Sunny
7   1/4/2017    mumbai           92          5    Rain
8   1/1/2017     paris           45         20   Sunny
11  1/4/2017     paris           42         10  Cloudy

In [24]:
import pandas as pd
india_weather = pd.DataFrame({
    "city":["mumbai","chennai","Delhi"],
    "temperatur":[44,50,24],
    "humidity":[41,43,34]
})

india_weather

      city  temperatur  humidity
0   mumbai          44        41
1  chennai          50        43
2    Delhi          24        34

In [25]:
import pandas as pd
us_weather = pd.DataFrame({
    "city":["newyork","chicago","orland"],
    "temperatur":[22,24,28],
    "humidity":[23,26,25]
})
us_weather

      city  temperatur  humidity
0  newyork          22        23
1  chicago          24        26
2   orland          28        25

In [ ]:
df_c = pd.concat([india_weather,us_weather])
df_c #check the index, it would have been taken from original data set

      city  temperatur  humidity
0   mumbai          44        41
1  chennai          50        43
2    Delhi          24        34
0  newyork          22        23
1  chicago          24        26
2   orland          28        25

In [28]:
df_c = pd.concat([india_weather,us_weather],ignore_index=True)

In [29]:
df_c

      city  temperatur  humidity
0   mumbai          44        41
1  chennai          50        43
2    Delhi          24        34
3  newyork          22        23
4  chicago          24        26
5   orland          28        25

In [30]:
df_c1 = pd.concat([india_weather,us_weather],keys=["india_weather","us_weather"])
df_c1

                    city  temperatur  humidity
india_weather 0   mumbai          44        41
              1  chennai          50        43
              2    Delhi          24        34
us_weather    0  newyork          22        23
              1  chicago          24        26
              2   orland          28        25

In [31]:
df_c1.loc["india_weather"]

      city  temperatur  humidity
0   mumbai          44        41
1  chennai          50        43
2    Delhi          24        34

In [35]:
temperature_df=pd.DataFrame({
    "city":["mumbai","chennai","delhi"],
    "temperature":[34,42,41]
},index=[0,1,2])
temperature_df

      city  temperature
0   mumbai           34
1  chennai           42
2    delhi           41

In [36]:
windspeed_df=pd.DataFrame({
    "city":["delhi","chennai"],
    "temperature":[34,42]
},index=[2,1])
temperature_df

      city  temperature
0   mumbai           34
1  chennai           42
2    delhi           41

In [37]:
pd.concat([temperature_df,windspeed_df],axis=1)

      city  temperature     city  temperature
0   mumbai           34      NaN          NaN
1  chennai           42  chennai         42.0
2    delhi           41    delhi         34.0

In [39]:
temperature_df=pd.DataFrame({
    "city":["mumbai","chennai","delhi"],
    "temperature":[34,42,41]
})
temperature_df

      city  temperature
0   mumbai           34
1  chennai           42
2    delhi           41

In [45]:
windspeed_df=pd.DataFrame({
    "city":["delhi","chennai"],
    "temperature":[34,42]
})
windspeed_df

      city  temperature
0    delhi           34
1  chennai           42

In [46]:
pd.merge(temperature_df,windspeed_df,on="city")

      city  temperature_x  temperature_y
0  chennai             42             42
1    delhi             41             34

In [ ]:
windspeed_df=pd.DataFrame({
    "city":["delhi","chennai","Telugana","kerela"],
    "temperature":[34,42,43,22]
})